words = [
    "extinctcoder",
    "mosquitto",
    "mqtt",
    "paho",
    "pydantic",
    "qos",
    "venv",
    "pycache",
    "levelname",
    "asctime",
    "mkdocs",
    "mkdocstrings",
    "powerstation",
    "formatter",
    "Formatter's",
    "Pydantic's",
    "behaviour",
    "sexualized",
    "sublicense",
    "NONINFRINGEMENT"
]
