services:
  home_assistant:
    image: ghcr.io/home-assistant/home-assistant:stable

    container_name: home_assistant
    hostname: home_assistant

    restart: unless-stopped

    ports:
      - 8123:8123

    volumes:
      - ./docker/home_assistant/config:/config
      - /etc/localtime:/etc/localtime:ro

    environment:
      - TZ=Asia/Dhaka

  mosquitto:
    image: eclipse-mosquitto:latest

    container_name: mosquitto
    hostname: mosquitto

    restart: unless-stopped

    ports:
      - 1883:1883
      - 9001:9001

    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - /etc/localtime:/etc/localtime:ro

    environment:
      - TZ=Asia/Dhaka

    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1883"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s

  powerstation_simulator:
    image: ps_sim:dev
    build:
      context: .
      dockerfile: ps_sim.dockerfile

    container_name: powerstation_simulator
    hostname: powerstation_simulator

    restart: unless-stopped

    depends_on:
      mosquitto:
        condition: service_healthy

    env_file:
      - .env.sample

    environment:
      - TZ=Asia/Dhaka
      - STATION_PREFIX=PS_001

    volumes:
      - ./src/powerstation_simulator:/app/src
